jenkinsci/atlassian-bitbucket-server-integration-plugin

src/main/java/com/atlassian/bitbucket/jenkins/internal/config/BitbucketTokenCredentialsImpl.java
src/main/resources/com/atlassian/bitbucket/jenkins/internal/config/BitbucketTokenCredentialsImpl/config.groovy

Icons were broken due to the plugin being renamed but the icon reference was not.
The credentials had an invalid field that meant it broke when trying to edit. Updated the groovy file to use the correct field name

Minor fixes

---

checkstyle.xml
pom.xml
src/main/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketClientFactoryImpl.java

Fix resource leak where responses were not closed properly.
Fix checkstyle to be buildable using only publicly available dependencies, as well as tidy up ruleset a bit.
Add exclusion for an OSGi package that is not available under java 11, that we do not use anyway.

Make project build

---

src/main/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketClientFactory.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketClientFactoryImpl.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/config/BitbucketSearchEndpoint.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketClientFactoryImplTest.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/fixture/BitbucketJenkinsRule.java
src/test/java/it/com/atlassian/bitbucket/jenkins/internal/config/BitbucketSearchEndpointIT.java
src/test/java/it/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMIT.java
src/test/resources/repo-filter-response.json

Move BitbucketRepositorySearchClient to use `<bitbucket-url>/rest/api/1.0/repos?projectName=<projectName>&name=<query>` because the other endpoint does not return the clone URL in older Bitbucket versions.
Also removes @Ignore from BitbucketSearchEndpointIT and ensures they all pass

Move BitbucketRepositorySearchClient to use Bitbucket project filter endpoint

---

src/main/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketClientFactory.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketClientFactoryImpl.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketWebhookSupportedEventsClient.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/client/exception/WebhookNotSupportedException.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/model/AtlassianServerCapabilities.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/model/BitbucketWebhookSupportedEvents.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketClientFactoryImplTest.java
src/test/resources/capabilities-response.json
src/test/resources/webhook-capabilities-response.json

We need to check if the remote Bitbucket Server support specific event
type before registering a web hook. The Factory client tests are
refactored so that multiple URL and their response can be mocked.

Support for fetching supported webhook event type

---

pom.xml

Lower version to match our internal instance, we do not need anything from a more modern version so lower is better (for reach). We can update as we need to when the need arises.

Lower minimum version

---

src/test/java/it/com/atlassian/bitbucket/jenkins/internal/config/BitbucketProjectConfigurationIT.java

Credentials and servers are now selected after comparing their `id`'s

Updated project configuration tests to be more robust. 

---

checkstyle.xml
src/test/java/it/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMIT.java

Adding Nonull as an illegal import as we should never use that (given we have package level annotations for that)
Adding google collections (guava) on the banned list as well so we don't have to look for it in PRs.

Add Nonnull and guava to illegal packages style

---

src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCM.java

This little fix means an error screen appears if incorrect credentials are passed through to the SCM rather than a stack trace.

Added form exception screen for inputting non-matching credentials

---

src/test/java/com/atlassian/bitbucket/jenkins/internal/config/BitbucketPluginConfigurationTest.java

Now the JSON size is tested to determine if a serverList needs to be set, the unit tests need to also include this info. We can't mock `JSONObject` so I've added an entry that resembles what should appear in typical execution to all tests.

Fixed failing plugin tests

---

pom.xml

but leaving the artifactId as it is, given we should not/cannot change it

Remove Atlassian from name and description

---

src/main/java/com/atlassian/bitbucket/jenkins/internal/trigger/BitbucketTriggerWorker.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/trigger/BitbucketTriggerWorkerTest.java

We didn't close the file descriptor properly, and so we were leaking them. This made some tests fail under windows. This PR fixes that problem

Fix leaking file descriptor

---

src/main/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketClientFactory.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketClientFactoryImpl.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketClientFactoryProvider.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketMirroredRepositoryDescriptorClient.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/client/HttpRequestExecutor.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/config/BitbucketSearchEndpoint.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/credentials/BitbucketCredentialsAdaptor.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/http/HttpRequestExecutorImpl.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/model/BitbucketMirror.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/model/BitbucketMirroredRepository.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/model/BitbucketMirroredRepositoryDescriptor.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/model/BitbucketMirroredRepositoryStatus.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/model/BitbucketPage.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketClientFactoryImplTest.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/config/BitbucketSearchEndpointTest.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMTest.java
src/test/java/it/com/atlassian/bitbucket/jenkins/internal/config/BitbucketProjectConfigurationIT.java
src/test/java/it/com/atlassian/bitbucket/jenkins/internal/config/BitbucketSearchEndpointIT.java
src/test/java/it/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMIT.java
src/test/resources/mirrored-repositories-response.json

* This endpoint will query Bitbucket upstream to get all the mirrored repository and then make a request to the mirror with the `selfLink` and verify if the repository is available on the mirror or not. It it's not available then the returned mirrored repository will have it's status set to `UNAVAILABLE`.
* Moved JSON parsing to `HttpRequestExecutor` because consumers of `HttpRequestExecutor` don't have to worry about parsing the response as it's being used in multiple places now.

* Added REST endpoint to get mirrored repositories for a given repository ID

---

src/main/java/com/atlassian/bitbucket/jenkins/internal/model/BitbucketPage.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/model/BitbucketProject.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCM.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMRepository.java
src/main/resources/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCM/config.groovy
src/main/webapp/js/searchableField.js
src/test/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMDescriptorTest.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMTest.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/trigger/BitbucketWebhookConsumerTest.java
src/test/java/it/com/atlassian/bitbucket/jenkins/internal/config/BitbucketProjectConfigurationIT.java
src/test/java/it/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMDescriptorIT.java
src/test/java/it/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMIT.java
src/test/java/it/com/atlassian/bitbucket/jenkins/internal/util/JsonUtils.java

* Remove projectKey and repoSlug fields from the form that were previously hidden and filled by javascript.
* There was a race condition between the form being submitted and the projectKey/repoSlug fields being filled with the javascript.
* Removing the projectKey/repoSlug fields removes the race condition.
* Calculate the projectKey/repoSlug on form submission instead
* Add some extra validation to the projectKey/repoSlug fields

Improve project repo config page

---

src/test/java/it/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMDescriptorIT.java

These tests failing in Bitbucket 6.X are addressed in this PR:
https://server-syd-bamboo.internal.atlassian.com/browse/PERS-MHEN-JDK11-4

Clone URL ignores 'admin@' prefix to url

---

pom.xml

We're getting this error:
```
java.lang.Error: Plugin command-launcher failed to start
at org.jvnet.hudson.test.PluginAutomaticTestBuilder$OtherTests.testPluginActive(PluginAutomaticTestBuilder.java:99)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
...
Caused by: hudson.util.CyclicGraphDetector$CycleDetectedException: Cycle detected: Plugin:command-launcher -> Plugin:script-security -> Plugin:junit -> Plugin:bouncycastle-api -> Plugin:command-launcher
at hudson.PluginManager$1$3$2$1.reactOnCycle(PluginManager.java:490)
at hudson.PluginManager$1$3$2$1.reactOnCycle(PluginManager.java:466)
at hudson.util.CyclicGraphDetector.detectedCycle(CyclicGraphDetector.java:64)
at hudson.util.CyclicGraphDetector.visit(CyclicGraphDetector.java:53)
at …
```

Exclude junit from script-security because of cyclic dependency

---

src/main/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketSearchHelper.java

The extra complexity (security problems with caching, concurrent modification, etc) is not worth the hassle right now and can be added in later if we think it is required. It is only done on user interaction so it is not a frequent operation anyway

Remove caching for BitbucketSearchHelper

---

src/main/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketCapabilitiesClientImpl.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCM.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketClientFactoryImplTest.java
src/test/resources/capabilities-missing-webhook.json

This should fix the problem with registering webhooks with Bitbucket 5.5 version

Fixing webhook related issues

---

src/main/java/com/atlassian/bitbucket/jenkins/internal/credentials/JenkinsToBitbucketCredentialsImpl.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/credentials/JenkinsToBitbucketCredentialsImplTest.java

Somewhere during one of the refactorings, null credentials were converted to empty credentials in BitbucketSCM. This made the client silently not use any credentials (anonymous credentials). This is reproducible when there are no credentials configured on the item. 
Let this be an example for future work for us to handle null towards the edge of the application and use a representation for the absence of value.

Guard against empty credentials

---

src/main/java/com/atlassian/bitbucket/jenkins/internal/config/BitbucketTokenCredentialsImpl.java
src/main/resources/com/atlassian/bitbucket/jenkins/internal/config/BitbucketTokenCredentialsImpl/config.groovy
src/test/java/com/atlassian/bitbucket/jenkins/internal/fixture/BitbucketMockJenkinsRule.java
src/test/java/it/com/atlassian/bitbucket/jenkins/internal/fixture/BitbucketJenkinsRule.java

Creating a new token doesn't require an ID to be set, but if one isn't provided when editing then it won't work.

JENKINS-59802 Add ID field to BitbucketTokenCredentialsImpl

---

src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCM.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketScmFormFillDelegate.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketScmFormValidationDelegate.java

When using the role based plugin you may not want to give overall configure to everyone. This changes the permission to the more correct and restrictive Item.CONFIGURE permission

JENKINS-60116 reduce required permissions

---

src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCM.java

Hi!
We have some global-library accessing scm.userRemoteConfigs during checkout and would be nice to access directly userRemoteConfigs
```
ERROR: groovy.lang.MissingPropertyException: No such property: userRemoteConfigs for class: com.atlassian.bitbucket.jenkins.internal.scm.BitbucketSCM
```
Regards,

Expose userRemoteConfigs on SCM class

---

src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCM.java

Addressing https://issues.jenkins-ci.org/browse/JENKINS-60809
This simply adds an override to the buildEnvironment that delegates the job to the GitSCM, making sure git variables in the pipeline are resolved correctly (the default SCM behaviour is to ignore them).

Added build environment override to SCM

---

src/main/java/com/atlassian/bitbucket/jenkins/internal/status/BitbucketBuildStatusFactory.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/status/BitbucketBuildStatusFactoryTest.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/status/BuildStatusPosterTest.java

This is required to keep the build status unique across multiple jobs for the same commit.

JENKINS-60956: Append full name of the `Job` to build status key  along with the build id

---

src/main/java/com/atlassian/bitbucket/jenkins/internal/trigger/BitbucketWebhookConsumer.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/trigger/BitbucketWebhookConsumerTest.java

Addressing https://issues.jenkins-ci.org/browse/JENKINS-60917
This is the same issue as JENKINS-60649 but manifesting in the consumer rather than the trigger impl, and the solution is the same (https://github.com/jenkinsci/atlassian-bitbucket-server-integration-plugin/pull/112)
Thanks to Daniel fixing the Java 10 bug with workflow jobs, we can finally func test them! I've added some here, and hope we can do something similar with the rest of our tests.

JENKINS-60917: first webhook build

---

src/main/resources/index.jelly

w/o this change, the current rendering is:
Note the trailing `_` after `Server`.

Fix html rendering

---

acceptance-tests/pom.xml
acceptance-tests/readme.md
acceptance-tests/src/main/java/it/com/atlassian/bitbucket/jenkins/internal/applink/oauth/client/JenkinsApplinksClient.java
acceptance-tests/src/main/java/it/com/atlassian/bitbucket/jenkins/internal/applink/oauth/client/JenkinsOAuthApi.java
acceptance-tests/src/main/java/it/com/atlassian/bitbucket/jenkins/internal/applink/oauth/client/JenkinsOAuthClient.java
acceptance-tests/src/main/java/it/com/atlassian/bitbucket/jenkins/internal/applink/oauth/model/OAuthConsumer.java
acceptance-tests/src/main/java/it/com/atlassian/bitbucket/jenkins/internal/applink/oauth/pageobjects/AuthorizeTokenPage.java
acceptance-tests/src/test/java/it/com/atlassian/bitbucket/jenkins/internal/applink/oauth/ThreeLeggedOAuthAcceptanceTest.java

- the `acceptance-tests` module/sub-directory to the repo
- a dependency on the Jenkins `acceptance-test-harness` framework inside that module + some other dependencies needed for the acceptance tests
- a page object for the OAuth (request token) authorization page
- simulates an OAuth dance by an end user:
-- get a new request token using the `/request-token` rest endpoint
-- redirect to the OAuth authorize page where user would authorize the request token
-- use the authorized request token to get an access token from the `/access-token` rest endpoint
- sets up project-level matrix authorization (e.g. build run permissions)
- checks that when triggering a build using an authenticated (via access token) `OAuthRequest`, the proper permissions are enforced
**Note:** the reason for the …

Integration testing project-matrix authorization of OAuth requests

---

src/main/java/com/atlassian/bitbucket/jenkins/internal/config/BitbucketServerConfiguration.java

Hello,
Our internal infrastructure is set up in a way that conflicts with the plugin. Bitbucket.org is part of the name of the host but it is a server installation.
I changed the check to look at the end of the hostname instead of whether it is in the name.

JENKINS-61915: Only reject servers whose name ends with bitbucket.org

---

src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketPostBuildStatus.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketRefNameExtractor.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketRefNameExtractorFactory.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCM.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMSource.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketPostBuildStatusTest.java

Based on the build type, the branch name we get from the `Revision` instance passed in to
`GitSCMExtension` (when invoked by `GitSCM`) can look different for the same branch: for most build types (e.g. `FreeStyleBuild`), the branch name is prefixed with `<repo-name>/`, but for multi-branch builds (` WorkflowRun`), the branch name is not prefixed with the repo name.
So, we check for the build type and extract the branch name accordingly, then prefix it with `refs/heads/` before including it in the data we post back to Bitbucket in `BitbucketPostBuildStatus`.

post the correct ref name to bitbucket

---

acceptance-tests/pom.xml
pom.xml
readme.md

This is necessary for our SSH work, but I've been warned about version issues even on master, so we should update our latest version (and document it) before we release 1.1.1

Jenkins version upgraded to 2.190

---

src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCM.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMSource.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMStep.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketScmFormFill.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketScmFormFillDelegate.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMDescriptorTest.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMStepDescriptorTest.java

Although JENKINS-60116 already has been closed in November 2019, the faulted
behaviour has not actually been fixed yet as reported by users in that ticket
this year and reproduced by myself.
The method `BitbucketSCMSource.DescriptorImpl.doFillCredentialsIdItems` was
obviously still doing a check for the global 'CONFIGURE' permissions (which
already explains the wrong behaviour and is redundant to the checks in the
called method `BitbucketScmFormFillDelegate.doFillCredentialsIdItems` anyway).
This commit adds the wanted behaviour of a context (item) based permission
check. If a context is given, only the `Item.EXTENDED_READ` permission is
required which follows the approach used by other SCM plugins (Git, Subversion).
Furthermore, the redundant checks are removed and the tests have been …

JENKINS-60116: Allow 'EXTENDED_READ' permission to select credentials

---

pom.xml

Update jackson version to fix security vulnerabilities.
Update parent pom to get latest enforcer rules and prevent bitrot

Bump depenendencies

---

acceptance-tests/pom.xml
pom.xml

Given we're releasing SSH, which is a relatively large feature, this release probably merits a minor version number.

Bumped to 2.1.0

---

src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMSource.java

When loading the BB SCM config form (e.g. as part of a multi-branch project), if the ssh credentials have been set, the non-ssh credentials (the "Credentials (for build auth)") dropdown is loaded as blank, even if a build credentials was selected and persisted.
That's because on loading the form, we get the current value for the `credentialsId` from the `CustomGitSCMSource` field of the `BitbucketSCMSource` entity, but that field is set to the ssh `credentialsId` if the ssh credentials are set (in `BitbucketSCMSource.initialize()`):
```
private void initialize(String cloneUrl, BitbucketSCMRepository bitbucketSCMRepository) {
repository = bitbucketSCMRepository;
String credentialsId = isBlank(bitbucketSCMRepository.getSshCredentialsId()) ?
bitbucketSCMRepository.getCredentialsId() : …
```

Empty build credentials dropdown value on BB SCM config form load

---

.gitignore
src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCM.java

Hi!
We have some global-library accessing scm.userRemoteConfigs during checkout and would be nice to access directly submoduleCfg like the standard git SCM.
```
ERROR: groovy.lang.MissingPropertyException: No such property: submoduleCfg for class: com.atlassian.bitbucket.jenkins.internal.scm.BitbucketSCM
```
It will also facilitate pipeline and jenkins library migration from GitSCM to BitbucketSCM.
Thanks!

Expose git submodule configs on bitucket SCM

---

src/main/java/com/atlassian/bitbucket/jenkins/internal/trigger/BitbucketWebhookConsumer.java

By default, the SCM API plugin considers a match if the `heads(SCMSource source)` returns a non-empty map (see [here](https://github.com/jenkinsci/scm-api-plugin/blob/041837a71e861a3cd7ade9269b2794b300c5ad47/src/main/java/jenkins/scm/api/SCMHeadEvent.java#L137)).
The way the `BitbucketSCMHeadEvent.heads` method is implemented is causing the `SCMHeadEvent.isMatch` method to return `true` in every single job in Jenkins, and because of that, the Branch API plugin is scanning all the jobs when any Multibranch Pipeline is triggered.
I've added some checks, as the Branch Source plugin [does](https://github.com/jenkinsci/bitbucket-branch-source-plugin/blob/cloudbees-bitbucket-branch-source-2.9.4/src/main/java/com/cloudbees/jenkins/plugins/bitbucket/hooks/PushHookProcessor.java#L143), to …

JENKINS-63815: Fix issue which matches all the jobs on head event

---

src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketExternalLink.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketJobLinkActionFactory.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketJobLinkActionFactoryTest.java

The BitbucketJobLinkActionFactory class is validating Bitbucket configurations the same way the form does, by checking project and repo via rest points. This is not a single call per action, and this method can be called 5 or 6 times per page load. Additionally, the validation _requires_ extended read permission for users- so a user without the ability to view job configuration will flood the logs with exceptions.
There are a few ways to solve this. The easiest is to simply remove the repo/project validation. This still performs the config validation, so it won't send you to an invalid URL, but does not verify the repo and project exist- so users will hit a dead link if it has been configured incorrectly rather than hiding it as was done previously.
I also removed the "CONFIG" …

Remove project and repo validation for bitbucket links

---

src/main/java/com/atlassian/bitbucket/jenkins/internal/applink/oauth/serviceprovider/auth/OAuth1aRequestFilter.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/jenkins/oauth/servlet/AuthorizeConfirmationConfig.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/applink/oauth/serviceprovider/auth/OAuth1aRequestFilterTest.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/jenkins/oauth/servlet/AuthorizeConfirmationConfigTest.java

1. Redirect unauthenticated users to the login screen when viewing the AuthorizeConfirmationConfig screen.
Previously, unauthenticated users with read access to Jenkins would not be prompted to log in. This would cause an
exception and show the user a stack trace when we tried to store the token. As a workaround, we will redirect
unauthenticated users to the login screen if security is enabled.
2. Update OAuth1aRequestFilter so that if security is not enabled we continue the filter chain.
Previously, the check for whether security was enabled or not was embedded deep in the authentication logic
and the fact that we didn't continue the filter chain was hard to spot. This commit refactors the logic so
that the check for whether security is enabled or not happens at the start of the method.

Bugfix: fix anonymous user oauth handling

---

src/main/resources/com/atlassian/bitbucket/jenkins/internal/jenkins/oauth/consumer/OAuthConsumerEntry/config.jelly

there was a bug with creating bbs consumer: clicking 'save' created error with JSON fields. 
tried to switch form entry field name to sharedSecret but there was still an error.
ended up switching form entry field name back to consumerSecret to match with backend. (so only the frontend text says sharedSecret, everything else still uses consumerSecret)

changed form entry field to still be consumer: bug fix

---

src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketScmFormFillDelegate.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketScmFormFillDelegateTest.java

Linked Issue: https://issues.jenkins.io/browse/JENKINS-61182
This involves a change in UI behaviour- previously, a partial project key could be entered (validation would complain), but then all repos matching the partial key would be matched and displayed. 
I argue this is not desirable behaviour- the form is intended to be completed in order, a partial project name is NEVER valid (in fact if you change it to a valid one, the repository field clears), and user can always visit bitbucket directly if they're unsure of the exact project key or name.

JENKINS-61182 repo form fill now only matches whole project names

---

src/main/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketSearchHelper.java

I think this is properly fixed now. I cannot replicate the behaviour in UI locally because of how `findAny()` works (it is non-deterministic, but on a local test instance behaves identically to `findFirst()`, which typically provides the correct answer). This can by creating a few test projects with subset project names/keys and identical repo names/slugs, and checking the length of the stream after both filter operations before and after this change.
This change impacts
- The validation of the repository field, not just the form fill
- The SCM, SCMSource and SCMStep when fetching the matching repository on config save. Both unmirrored and mirrored repos use the same helper method
Let me know if I missed anything

Added project match check in validation and SCM constructor steps

---

src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/SelectBranchTrait.java
src/main/resources/com/atlassian/bitbucket/jenkins/internal/scm/SelectBranchTrait/help.groovy
src/main/resources/com/atlassian/bitbucket/jenkins/internal/scm/SelectBranchTrait/help.properties
src/main/resources/com/atlassian/bitbucket/jenkins/internal/trigger/BitbucketWebhookMultibranchTrigger/config.groovy

FEATURES: 
- push trigger checkbox is default selected 
- help dialogue to pull request filter behaviour (checked with @ctan-atlassian)

ref trigger checked default & help text for select branch trait

---

acceptance-tests/pom.xml
pom.xml
readme.md
src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCM.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMSource.java
src/test/java/it/com/atlassian/bitbucket/jenkins/internal/config/BitbucketPluginConfigurationIT.java

Specifically
* update minimum supported Jenkins version from 2.204.1 to 2.204.6
* Remove dependency on workspace-aggregator as it was causing more problems than it solved, now added the specific dependencies in.
* Ordered the dependencies alphabetically to make it easier to manage.
* Updated dependent plugin versions, most notably the Git plugin lifted to 4.4.5 (latest we can use with our current minimum Jenkins version)
* Updated many plugin versions
* Made jackson-databind be versioned the same as the rest of the jackson dependencies
* Remove a check for the credential in the plugin config, as we've removed that particular input some versions back
* Added two findbug exclusions for things that arguably are false positives

Fix the builds by updating minimum versions.

---

src/main/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketCapabilitiesClient.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketCapabilitiesClientImpl.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketClientFactory.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketClientFactoryImpl.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketDeploymentClient.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketDeploymentClientImpl.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketRepositoryClient.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketRepositoryClientImpl.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/deployments/BitbucketDeploymentFactory.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/deployments/BitbucketDeploymentFactoryImpl.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/deployments/package-info.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/model/AtlassianServerCapabilities.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/model/deployment/BitbucketCDCapabilities.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/model/deployment/BitbucketDeployment.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/model/deployment/BitbucketDeploymentEnvironment.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/model/deployment/BitbucketDeploymentEnvironmentType.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/model/deployment/DeploymentState.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/model/deployment/package-info.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/status/BuildStatusPoster.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketClientFactoryImplTest.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketDeploymentClientImplTest.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketRepositoryClientImplTest.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/deployments/BitbucketDeploymentFactoryImplTest.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/fixture/mocks/TestBitbucketClientFactoryHandler.java
src/test/resources/deployments/send_deployment_request.json
src/test/resources/deployments/send_deployment_result.json

Bitbucket Server is looking into showing deployment status on pull requests and commits. This is the first PR to the feature branch `feature/deployment-notifications` with the client code to:
* Create a deployment status object that aligns with Bitbucket's unreleased REST API
* Send that object to Bitbucket Server
Future PRs will handle recognising when a deployment has happened. They will most likely be in the form of a `Notifier` step that consumers can use for freestyle jobs and a `BuildWrapper` that consumers can use to wrap the deployment steps on a pipelines job

Add client for interacting with Bitbucket DC's upcoming deployment status API

---

src/main/resources/com/atlassian/bitbucket/jenkins/internal/jenkins/oauth/token/OAuthTokenConfiguration/index.properties

Tracking ticket: https://issues.jenkins.io/browse/JENKINS-66372
See below screenshot before and after:

JENKINS-66372 changed oauth date to use month instead of minutes

---

acceptance-tests/src/main/java/it/com/atlassian/bitbucket/jenkins/internal/util/BitbucketUtils.java
acceptance-tests/src/test/java/it/com/atlassian/bitbucket/jenkins/internal/SmokeTest.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMSource.java

I believe the checkout was failing because the Git SCM is resolving the credentials by ID, which id does using it's parent (the SCM owner) as context. This is typically set by Stapler but as we wrap the SCM, it was set to null, which the credentials provider resolves as Jenkins.get(), so folder-scoped credentials were inaccessible.
I've added a manual SCM owner assignment to the `BitbucketSCMSource`, and acceptance tests for both freestyle and MBP jobs at the folder level.

JENKINS-65541 add owner to git scm, add func tests for folder credentials

---

src/main/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketCapabilitiesClient.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketCapabilitiesClientImpl.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/deployments/DeployedToEnvironmentNotifierStep.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/deployments/DeploymentPosterImpl.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/model/deployment/BitbucketCDCapabilities.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/deployments/DeployedToEnvironmentNotifierStepTest.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/deployments/DeploymentPosterImplTest.java

The capabilities endpoint was changed before the release in Bitbucket 7.16. The released version returns a map as the response.

Update capabilities checker to expect a map response

---

src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMSource.java

On restart, the job config is read into memory. However because the SCM Source does not contain an ID, it gets auto-generated each time. This means that on a scan, Jenkins detects that the SCM has 'changed' and therefor a build should be run for all branches (causing a 'build storm').
This change sets a static ID so that it is saved in the XML and on scanning after restarts does not trigger a build storm.

Add ID to gitSCMSource so that it is persisted in the XML and not generated to be a random UUID each time

---

.gitignore

This is useful to make backups of the work folder without it being noticed by git

Update pattern for gitignore Jenkins homedir to include any folder that is prefixed with 'work'

---

acceptance-tests/pom.xml
pom.xml
readme.md

It seems in order to get all the tests green we need to lift the minimum version we support. This PR moves us from  2.222.4 released 2020-05-24
to 2.235.5 released 2020-08-17.
We are moving from 2.222 to 2.235 which is the next lts version, so we're only dropping support for one LTS version, despite the big jump in version number.

Upgrade Jenkins min version

---

src/test/java/it/com/atlassian/bitbucket/jenkins/internal/trigger/BitbucketWebhookTriggerImplTest.java

This test is frequently red for no good reason. Adding `@Ignore` so it won't be so disruptive. We can then later either look at removing or fixing it.

Ignore a test that is very unstable

---

src/main/java/com/atlassian/bitbucket/jenkins/internal/jenkins/oauth/consumer/OAuthGlobalConfiguration.java

I chose security given this is auth configuration, but I'm happy to change it to System Config if anyone feels strongly about it.

Categorize oauth consumer global config as Security rather than Uncategorized

---

acceptance-tests/pom.xml
acceptance-tests/src/main/java/it/com/atlassian/bitbucket/jenkins/internal/pageobjects/BitbucketScmWorkflowMultiBranchJob.java
pom.xml
readme.md

A dependency change in our acceptance test framework means we need to bump our latest Jenkins up to 2.2491, which had a CSS change that broke our func tests. This PR addresses both- for release in 3.0.2.

Acceptance test fix

---

src/test/java/it/com/atlassian/bitbucket/jenkins/internal/deployments/AbstractDeploymentStatusPosterIT.java
src/test/java/it/com/atlassian/bitbucket/jenkins/internal/status/BuildStatusPosterIT.java
src/test/java/it/com/atlassian/bitbucket/jenkins/internal/trigger/TriggerWebhookCreationTest.java
src/test/java/it/com/atlassian/bitbucket/jenkins/internal/util/BitbucketUtils.java

If a test times out using the Timeout rule the `@After` and `@AfterClass` methods don't get called to clean up the repository. This can lead to failures in other tests if they are trying to create a fork with the same name. Instead, we will create a fork with a unique name so that if the cleanup fails to run it does not impact on other tests.

Ensure test repos have unique names

---

acceptance-tests/pom.xml
acceptance-tests/src/main/java/it/com/atlassian/bitbucket/jenkins/internal/pageobjects/BitbucketScmConfig.java
acceptance-tests/src/main/java/it/com/atlassian/bitbucket/jenkins/internal/test/acceptance/ProjectBasedMatrixSecurityHelper.java
pom.xml
readme.md
src/test/java/it/com/atlassian/bitbucket/jenkins/internal/fixture/JenkinsProjectHandler.java
src/test/java/it/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMDescriptorIT.java

* Add dependency management on bom and remove versions that are managed by that
* Harden acceptance tests
* Remove dependency on trilead-ssh2 (it seems to not be needed)

Bump Jenkins to 2.289.1

---

checkstyle.xml
src/main/java/com/atlassian/bitbucket/jenkins/internal/link/BitbucketJobLinkActionFactory.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/link/BitbucketMultibranchLinkActionFactory.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/status/BuildStatusPoster.java

Our checkstyle config _tried_ to prevent import of the `NonNull` annotation but it had put the config in the wrong place. This fixes that mistake.

Fix checkstyle config, and update style to match the now enforeced style

---

acceptance-tests/pom.xml

This PR fixes this [test](https://server-syd-bamboo.internal.atlassian.com/browse/BSERVTOOLS-BBSJEN-ST-532/test/case/4155528789) which is failing because of a change in button with label "Add user or group...". The corresponding fix in the acceptance-test-harness library is done in [this PR](https://github.com/jenkinsci/acceptance-test-harness/pull/720) and hence we need a version bump in that library which is done in this PR.

Bump acceptance-test-harness version to fix Smoke tests

---

checkstyle.xml
src/main/java/com/atlassian/bitbucket/jenkins/internal/client/ModernBitbucketBuildStatusClientImpl.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/http/HttpRequestExecutorImpl.java

The log4j API that Jenkins provides actually comes from SLF4J so this really doesn't do much but it stops customers who are nervous about the Log4Shell VULN from asking why we're using `org.apache.log4j` classes.

Remove all usages of Log4j API and ban it

---

pom.xml
readme.md
src/main/java/com/atlassian/bitbucket/jenkins/internal/trigger/register/BitbucketWebhookHandler.java

- Changed the value of `bitbucket.version` to 6.10.0 in `pom.xml`
- Fix `BitbucketWebhookHandler` to not send "pr:from_ref_updated" in the webhooks request for Bitbucket < 7.0

Bump bitbucket version to 6.10.0

---

pom.xml
readme.md
src/main/java/com/atlassian/bitbucket/jenkins/internal/trigger/register/BitbucketWebhookHandler.java

Windows build doesn't pass with bitbucket version 6.10.0 and hence this PR bumps the version to 6.10.15. Also an unused import is removed to fix checkstyle build.
Regarding failing builds, it seems the windows build needs at least 6.10.15 which has [SSH related change](https://jira.atlassian.com/browse/BSERV-13013?jql=project%20%3D%20BSERV%20AND%20resolution%20in%20(Fixed%2C%20Done)%20AND%20fixVersion%20%3D%206.10.15%20ORDER%20BY%20votes%20DESC). This is verified by running the builds on 6.10.14 and 6.10.15 -

Set bitbucket version to 6.10.15

---

readme.md

Also rename 'personal' access tokens to 'HTTP' access tokens now that project/repo scoped tokens can be created in Bitbucket Server.
Thanks to @mikerossiter for [pointing this out](https://github.com/jenkinsci/atlassian-bitbucket-server-integration-plugin/pull/322)

Fix broken access token URL

---

readme.md

We can still test successfully against 5.5 so I don't think it's correct to say we don't support it. Even if the feature set is much smaller, the plugin works as intended and our capability endpoint gives info to users attempting to use unavailable features.
The change related to our windows builds- because we're testing jenkins rather than Bitbucket, I don't think it's necessary for Bitbucket 5.5 to work on Windows for us to say the plugin is compatible with Bitbucket 5.5 on Windows.

Revert minimum supported version to 5.5

---

readme.md
src/main/java/com/atlassian/bitbucket/jenkins/internal/config/BitbucketPluginConfiguration.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMStep.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/config/BitbucketPluginConfigurationTest.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMStepTest.java
src/test/java/it/com/atlassian/bitbucket/jenkins/internal/fixture/TestSCMStep.java
src/test/java/it/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMSnippetGeneratorIT.java
src/test/java/it/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMStepIT.java

This adds the ability to declare a human-readable Bitbucket server instance name as so:
```
bbs_checkout branches: [[name: '*/master']], credentialsId: 'fe048ca8-1461-41ff-bfe1-f40ebd29e92c', projectName: 'Project 1', repositoryName: 'jenkins', serverName: 'Bitbucket'
```
Note that using a server id will still work fine. There are a few cases to consider
- Server names are not unique- if multiple matching server names are found, we kick back an error requesting to use an id instead (but you can still use both for readability)
- Names are case sensitive and must appear exactly as they're edited on the config page (including whitespace etc.). If the strings aren't equal we error
- Sever id always takes precedence over name
- This _technically_ makes both id and name optional, but trying to …

JENKINS-66498 add server name resolution for BitbucketSCMStep

---

src/main/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketCapabilitiesClientImpl.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketClientFactoryImpl.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketCapabilitiesClientImplTest.java

Our capability cache was being initialized in the client constructor, which meant every call being made to that client was using a fresh cache.
I've made the cache static and moved initialization to `getServerCapabilities` so we don't make repeated calls across multiple clients.

Fix capability cache

---

src/main/java/com/atlassian/bitbucket/jenkins/internal/jenkins/oauth/consumer/OAuthConsumerCreateAction.java
src/test/java/upgrade/com/atlassian/bitbucket/jenkins/internal/UpgradeTest.java

The upgrade test did not use the correct annotation when filtering classes, that is fixed in this PR

Fix upgrade test to load the annotation from the correct classloader

---

src/main/java/com/atlassian/bitbucket/jenkins/internal/jenkins/oauth/consumer/OAuthGlobalConfiguration.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/jenkins/oauth/token/OAuthTokenConfiguration.java
src/main/resources/com/atlassian/bitbucket/jenkins/internal/jenkins/oauth/consumer/OAuthConsumerCreateAction/sidepanel.jelly
src/main/resources/com/atlassian/bitbucket/jenkins/internal/jenkins/oauth/consumer/OAuthConsumerUpdateAction/sidepanel.jelly
src/main/resources/com/atlassian/bitbucket/jenkins/internal/jenkins/oauth/consumer/OAuthGlobalConfiguration/index.jelly
src/main/resources/com/atlassian/bitbucket/jenkins/internal/jenkins/oauth/token/OAuthTokenConfiguration/sidepanel.jelly

The change proposed prepares the plugin for the icon path removal from core in the upcoming LTS line. This change affects plugins not using the icon API or relying on paths. Plugins using the API properly in the first place are unaffected by this 
change.
Additionally I've removed the mainpanel icon, because that's what modern Jenkins does look like.
Could you trigger a release after merging this PR please, giving people a chance to update the plugin before updating to the next LTS version @mhenschke-atl 
Thanks in advance!

Adapt icon path removal from core

---

pom.xml

It looks like instance-identity was [removed from the BOM](https://github.com/jenkinsci/bom/releases) which is causing the plugin to fail to compile when depending on latest Jenkins.
The plugin was previous using version 2.2 and that appears to be what's in use [across other Jenkins plugins](https://mvnrepository.com/artifact/org.jenkins-ci.modules/instance-identity?repo=jenkins-releases) so I've opted to keep it the same.

Added explicit version for instance identity module

---

pom.xml
readme.md

Despite both issues being bugs, I think the changes to our webhook handling are sufficiently large to merit a minor version release, but open to opinions.

Bumped minor version to 3.3.0

---

src/main/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketBuildStatusClient.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketBuildStatusClientImpl.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketClientFactoryImpl.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketProjectClientImpl.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketRepositoryClient.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketRepositoryClientImpl.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/client/ModernBitbucketBuildStatusClientImpl.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/model/BitbucketBuildStatus.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/model/BitbucketCICapabilities.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/model/BuildState.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/status/BitbucketBuildStatusFactory.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/status/BitbucketBuildStatusFactoryImpl.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/status/BuildStatusPoster.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketBuildStatusClientImplTest.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketRepositoryClientImplTest.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/client/ModernBitbucketBuildStatusClientImplTest.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/fixture/mocks/TestBitbucketClientFactoryHandler.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/model/BitbucketBuildStatusTest.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/status/BitbucketBuildStatusFactoryImplTest.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/status/BuildStatusPosterTest.java
upload-to-jwar.sh

Adds the "cancelled" build status to supporting instances (Bitbucket 8.0 and above), and cleans up the handling of the different types of statuses we send

Support for cancelled build state

---

src/main/java/com/atlassian/bitbucket/jenkins/internal/provider/DefaultGlobalLibrariesProvider.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/provider/GlobalLibrariesProvider.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/status/BitbucketBuildStatusFactory.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/status/BitbucketBuildStatusFactoryImpl.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/status/BuildStatusPoster.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/status/LocalSCMListener.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/status/BitbucketBuildStatusFactoryImplTest.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/status/BuildStatusPosterTest.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/status/LocalSCMListenerTest.java
src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker

Fixes the bug where the build status is not sent correctly when global pipeline libraries are used in a job.
https://issues.jenkins.io/browse/JENKINS-69268?filter=-1
This change ensures that build status is sent to all repos used in the job, except for repos hosting a global pipeline library.
I still need to perform testing with a freestyle job and a pipeline job and write extra unit tests.
- [] Ensure that the pull request title represents the desired changelog entry - WIP PR - N/A 
- [] Link to relevant pull requests, esp. upstream and downstream changes

JENKINS-69268-fix-bitbucket-shared-library-build-status

---

Jenkinsfile
acceptance-tests/pom.xml
acceptance-tests/readme.md
acceptance-tests/src/main/java/it/com/atlassian/bitbucket/jenkins/internal/pageobjects/BitbucketScmConfig.java
acceptance-tests/src/main/java/it/com/atlassian/bitbucket/jenkins/internal/pageobjects/BitbucketScmWorkflowJob.java
acceptance-tests/src/main/java/it/com/atlassian/bitbucket/jenkins/internal/pageobjects/BitbucketScmWorkflowMultiBranchJob.java
acceptance-tests/src/test/java/it/com/atlassian/bitbucket/jenkins/internal/SmokeTest.java
acceptance-tests/src/test/java/it/com/atlassian/bitbucket/jenkins/internal/applink/oauth/ThreeLeggedOAuthAcceptanceTest.java
pom.xml
readme.md
src/test/java/com/atlassian/bitbucket/jenkins/internal/util/TestUtils.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/util/TestUtilsTest.java
src/test/resources/cr-line-endings.txt
src/test/resources/lf-line-endings.txt

Bumping the Jenkins version to resolve [vulnerabilities](https://www.jenkins.io/security/advisory/2023-03-08/).
Updated the readme with steps to run the acceptance tests on macOS.

None bump Jenkins to 2.375

---

src/test/java/it/com/atlassian/bitbucket/jenkins/internal/fixture/BitbucketJenkinsRule.java

In the most recent version of Jenkins, `Ajax.Request` usage has been removed in favor of the JavaScript fetch API (e.g. [combobox.js](https://github.com/jenkinsci/jenkins/pull/7900/files)).
This PR enables the fetch polyfill for the test harness web client, ensuring tests are compatible with newer Jenkins versions.

Enable fetch polyfill for test harness web client

---

src/main/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketFilePathClientImpl.java

Fix "Invalid URI: noSlash" on scenario where the "jenkinsfile" file is on a subpath.
Sorry for not following the checklist but I believe the fix is simple to understand and probably a bug introduced by mistake on the last refactoring done for version 3.4.0.

Fix addPathSegment on scmFile.getFilePath

---

acceptance-tests/pom.xml
acceptance-tests/src/main/java/it/com/atlassian/bitbucket/jenkins/internal/pageobjects/BitbucketScmWorkflowJob.java
pom.xml
readme.md

This fixes https://github.com/jenkinsci/atlassian-bitbucket-server-integration-plugin/security/dependabot/37

The minimum version of Jenkins changed to be 2.401.1

---

src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketPullRequestDiscoveryTrait.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMHeadDiscoveryHandler.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMSource.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMSourceContext.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketPullRequestDiscoveryTraitTest.java

Lets the PR discovery handler avoid having to fetch all open PRs if the retrieve was triggered by a webhook event. This is done via the following changes
* Pass the heads from `SCMHeadEvent#heads` into the `BitbucketSCMSourceContext`
* Update `BitbucketPullRequestDiscoveryTrait#decorateContext` so that it checks if the context has the "event heads"
* If event, heads are present simply use these as the return value for `BitbucketSCMHeadDiscoveryHandler#discoverHeads()`
* Otherwise, fetch all open PRs from Bitbucket

Use event heads in PR discovery handler if present

---

src/main/java/com/atlassian/bitbucket/jenkins/internal/status/BitbucketBuildStatusFactoryImpl.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/status/BitbucketRevisionAction.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/status/BuildStatusPoster.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/status/LocalSCMListener.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/status/LocalSCMListenerTest.java

When Jenkins receives branches, they arrive in the form provided by a git fetch in the form `remotes/reponame/branchname`, which the GitSCM resolves to a simple branch name. Tags however appear in the form `refs/tags/tagname` and the GitSCM does not resolve provide a facility for this to be resolved- consequently when we receive the tag, we attempt to reduce it to a branch name and then blindly append `refs/heads` to it, causing an invalid identifier.
This change checks the `GIT_BRANCH` variable to determine if the value is a tag- if it does, it passes it along as normal, otherwise processes the branch name as it did before.
While I was here, I also addressed the issue of the logs attempting to print the entire build status to the listener rather than the state, so in the console logs of …

JENKINS-71289 create correct ref name for tags when posting build status

---

src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketPullRequestDiscoveryTrait.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketPullRequestSourceBranch.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/status/LocalSCMListener.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketPullRequestDiscoveryTraitTest.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/status/LocalSCMListenerTest.java

The new `BitbucketPullRequestSCMHead` uses `PR-{id}` as the format for the head name. This means that when the build status is posted back to bitbucket it uses that as the ref name. This PR modifies this so that it uses the PR source branch instead.

Use PR source branch for build status

---

src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketPullRequestDiscoveryTrait.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketPullRequestSourceBranch.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/status/LocalSCMListener.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketPullRequestDiscoveryTraitTest.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/status/LocalSCMListenerTest.java

The plugin is merging the wrong direction when building PRs. For example, if We have a PR from source -> master, in the build logs we have:
```
Merging master commit 15292fb296688ce9cc0543baf48e183cb4a821cc into PR head commit 783f4bd57afe9bfdd105b143531493dc9449aca8
```
Which is wrong, it should merge 783f4bd5 into 15292fb29 (which is the master commit)
This PR solves this by using `PreBuildMerge` instead of `MergeWithGitSCMExtension`.
Example log after the fix:
```
Merging Revision 783f4bd57afe9bfdd105b143531493dc9449aca8 (origin/PR-1) to origin/master, UserMergeOptions{mergeRemote='origin', mergeTarget='master', mergeStrategy='DEFAULT', fastForwardMode='FF'}
```

Fix merge direction

---

pom.xml

Disable the jacoco integration, we don't use it anyway and it makes reviews harder for us.

Disable jacoco coverage

---

src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketPullRequestDiscoveryTrait.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketPullRequestSourceBranch.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/status/LocalSCMListener.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketPullRequestDiscoveryTraitTest.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/status/LocalSCMListenerTest.java

Includes the following changes to allow support for forked pull requests.
* Change refspec to use the Bitbucket custom `refs/pull-requests/{id}/from` ref to map the PR source ref
* Remove the ref restriction when posting a build status for PR builds to the target repo. This is made possible because the source commit is available in the target repo via the `refs/pull-requests/{id}/from` ref.

Add support for forked pull requests

---

acceptance-tests/src/main/java/it/com/atlassian/bitbucket/jenkins/internal/pageobjects/BitbucketBranchSource.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketBranchDiscoveryTrait.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketBranchSCMHead.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMHead.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMProbe.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMRevision.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMSource.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/trait/BitbucketLegacyTraitConverter.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/trigger/BitbucketWebhookConsumer.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketBranchClientImplTest.java

This PR contains the changes require to replace the `BranchDiscoveryTrait` with the new `BitbucketBranchDiscoveryTrait`.

Replace BranchDiscoveryTrait with BitbucketBranchDiscoveryTrait

---

src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketBranchSCMHead.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketPullRequestSCMHead.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMHead.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/filesystem/BitbucketSCMFileSystem.java
src/test/java/it/com/atlassian/bitbucket/jenkins/internal/scm/filesystem/BitbucketSCMFileSystemIT.java

Fix lightweight checkout for multibranch pipelines. The `BitbucketSCMFileSystem` was not recognising the `BitbucketBranchScmHead` & `BitbucketPullRequestScmHead` as it expected `GitScmHead`.

Fix Jenkins PR support lightweight checkout

---

src/main/java/com/atlassian/bitbucket/jenkins/internal/jenkins/oauth/consumer/OAuthConsumerCreateAction.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/jenkins/oauth/consumer/OAuthConsumerUpdateAction.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/jenkins/oauth/consumer/OAuthGlobalConfiguration.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/jenkins/oauth/token/OAuthTokenConfiguration.java

Update the icon of the "Manage Bitbucket Server consumers" menu under "Manage Jenkins".
The idea is to harmonize the look and feel of the page since most other plugins and especially the core functions there also use these kind of icons.
I opted with built-in icons from [Jenkins core](https://github.com/jenkinsci/jenkins/tree/master/war/src/main/resources/images/symbols) to not introduce any new dependencies.
Manual starting local instance, comparing results.
**Before**
**After**
```[tasklist]
```

Update OAuth configuration icons

---

src/test/java/it/com/atlassian/bitbucket/jenkins/internal/deployments/FreestyleDeploymentStatusPosterIT.java
src/test/java/it/com/atlassian/bitbucket/jenkins/internal/deployments/PipelineDeploymentStatusPosterIT.java
src/test/java/it/com/atlassian/bitbucket/jenkins/internal/status/BuildStatusPosterIT.java

We have been naughty and used wiremock provided apache http classes. We should not, it make upgrades etc hard. This changes the usages to their proper dependencies which was already present in our pom.xml

Remove usages of wiremocks shaded apache http classes to ease upgrades

---

src/main/java/com/atlassian/bitbucket/jenkins/internal/http/HttpRequestExecutorImpl.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/util/SystemPropertiesConstants.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/http/HttpRequestExecutorImplTest.java

[Http timeout for bitbucket server is not configurable](https://issues.jenkins.io/browse/JENKINS-71610?filter=-2)
Added two system porperties:
bitbucket.http.connect.timeout=10000 (ms)
bitbucket.http.request.timeout=10000 (ms)
Which are propagated to the okhttp client
Added unit test
```[tasklist]
- [? ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ x] Ensure that the pull request title represents the desired changelog entry
- [x ] Please describe what you did
- [ x] Link to relevant issues in GitHub or Jira
- [? ] Link to relevant pull requests, esp. upstream and downstream changes
- [ x] Ensure you have provided tests - that demonstrates feature works or fixes the issue
```

Support timeout configuration for Http connection to bitbucket server (bitbucket.http.connect.timeout & bitbucket.http.request.timeout)

---

src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMRevision.java

There is no integration testing for this (as we don't and probably shouldn't rely on the ignore committer plugin), but a local test demonstrates the ignored commiters plugin can now create a GitSCMFileSystem without error, and the plugin is working as expected.
Only the commit with an allowlisted committer has a build status
And Jenkins does not have a build for the ignored commiter

JENKINS-72071 update SCM Revision to extend from git plugin

---

pom.xml
src/main/java/com/atlassian/bitbucket/jenkins/internal/http/HttpRequestExecutorImpl.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/util/SystemPropertiesConstants.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/http/HttpRequestExecutorImplTest.java

Increased the timeouts slightly to allow slower environments to function. 
Formatted the code to adhere to our code style

NONE checkstyle fixes, increased default timeouts to 30s to minimise surprises

---

acceptance-tests/pom.xml
pom.xml

Bumping bom version to `2661.vb_b_60650f6d97` to resolve `BitbucketProjectConfigurationIT` test failures.
Bumping the following other dependencies to resolve maven upper bound enforcer issues:
- jackson 
- commons-lang3
Confirmed that the build now passes.
```[tasklist]
```

Bump bom version to resolve internal build failures

---

readme.md
src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketScmFormFillDelegate.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketScmFormValidationDelegate.java

In our current version of the git plugin (org.jenkins-ci.plugins:git:5.0.2), secret text credentials are not a supported credential type. They can't be resolved by the plugin, and so an unauthenticated request is sent and inevitably fails. To resolve this, I've changed our plugin to:
- No longer include secret text credentials as an option in the SCM form fill delegate
- Provide a form validation error if those credentials are selected (in the reasonably unlikely event a user already has job configuration with a secret text credential configured).
I've run a manual test of this, there is no automated testing for the credential validation at all unfortunately. Were I to guess, it's because our credentials are resolved using the static method `CredentialsUtils#getCredentials` which can't be …

JENKINS-72280 remove secret text as selectable option in forms

---

readme.md

Make note that upgrading from 3.5.0 to 3.6.0 may cause stale data, in regards to the change of `branchName` to `refName`

Update 3.6.0 changelog entry

---

src/test/java/com/atlassian/bitbucket/jenkins/internal/config/BitbucketPluginConfigurationTest.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/status/LocalSCMListenerTest.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/trigger/BitbucketWebhookConsumerTest.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/util/SerializationFriendlySCM.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/util/SerializationFriendlyTrigger.java

Under Java 17 it is not possible to serialize mocks without add-opens. This rewrites a handful of tests to avoid serializing mocks by introducing a class that simply skips over the mock when serializing, and so it works under Java 17 without adding add-opens.
This is not super elegant, but it has the benefit of working.

Rewrite tests to not serialize mocks

---

src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMSource.java

Adds the `@UpgradeHandled` annotation to `REFSPEC_TAGS` as `REFSPEC_TAGS` uses the same `{remote}` variable in `REFSPEC_DEFAULT`. This should be safe for upgrade & has been tested locally.

NONE Upgrade handle REFSPEC_TAGS

---

readme.md
src/main/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketCommitClient.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketCommitClientImpl.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketRepositoryClient.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketRepositoryClientImpl.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/model/BitbucketCommit.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketBranchSCMHead.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMSource.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketScmHelper.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketCommitClientImplTest.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketRepositoryClientImplTest.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMSourceTest.java
src/test/resources/commit.json
src/test/resources/open-pull-request.json

Addresses [JENKINS-73267](https://issues.jenkins.io/browse/JENKINS-73267) by fetching the latest head in `SCMSource#retrieve(SCMHead head, TaskListener listener)`, for pull request / branch SCMHeads (with corresponding new client methods to get the data from Bitbucket).
- unit tests
- manual tests
- using reproduction steps in JENKINS-73267 for multibranch pipelines (one to discover branches, one to discover pull requests)

JENKINS-73267 make SCMSource retrieve latest head from bitbucket instead of cached value

---

readme.md
src/main/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketCommitClientImpl.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketTagClientImpl.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketCommitClientImplTest.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketTagClientImplTest.java
src/test/resources/commit.json
src/test/resources/tags.json

Branch and tag names with slashes could not be built due to not encoding the slashes for the query parameter. Adds url encoding to the branch / tag name. 
The exception shouldn't be thrown unless your JVM doesn't support "UTF-8" encoding. 
* Manual testing was carried out against both tags & branches. 
* Integration and unit testing has also been performed.

JENKINS-73871 Fix tag and branch names not building with slash in it

---

pom.xml

replaces the direct dependency on eddsa with the eddsa-api library plugin.
Bumps minimum Jenkins version and bom to accomodate
none

replace direct eddsa library with api plugin

---

src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketPRBranchNameDecorator.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketPREnvironmentContributor.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMSource.java
src/main/java/com/atlassian/bitbucket/jenkins/internal/status/LocalSCMListener.java

When we introduced the`BitbucketPullRequestSCMHead` we accidentally changed the value of a number of variables. This puts those variables back to what they should be. This included the `GIT_BRANCH` variable which was used by the `BuildStatusPoster` to post the build status.
Unfortunately  the `WorkflowRun` and `WorkFlowJob` are `final` which makes writing unit tests very hard, so I opted for not doing any tests :( Most of the new code is pretty basic so while a unit test would be beneficial I don't think it is disastrous without it.

JENKINS-74782 fix build status ref

---

readme.md
src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/trait/BitbucketTagDiscoveryTrait.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/scm/trait/BitbucketTagDiscoveryTraitTest.java

When multiple discovery behaviours are enabled the decorateBuilder may be called multiple times with different heads.
This ensures that calling the method with a different head type does no throw any exception, instead the head is
just ignored.

JENKINS-74736 fix class cast exception

---

src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMSource.java
src/test/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMSourceTest.java

* Fixed JENKINS-75494 - PR builds not correctly having refs populated when a fork is used in a PR.
* This occurs due to the Jenkins user making the checkout not having appropriate access to the forked repository

JENKINS-75494 Fix pr builds not getting correct refs
