- src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCM.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/trigger/BitbucketWebhookConsumer.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/trigger/BitbucketWebhookTriggerRequest.java
- src/test/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMTest.java
- src/test/java/com/atlassian/bitbucket/jenkins/internal/trigger/BitbucketWebhookConsumerTest.java
- src/test/java/it/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMIT.java
* Trigger build for projects configured with `BitbucketSCM` SCM when refs changed webhook is received
* `BitbucketWebhookConsumer` code has been refactored to make it more readable.
> Trigger build for projects configured with `BitbucketSCM`

- checkstyle.xml
- src/main/java/com/atlassian/bitbucket/jenkins/internal/config/BitbucketPluginConfiguration.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/config/BitbucketSearchEndpoint.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/trigger/BitbucketWebhookConsumer.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/trigger/BitbucketWebhookEndpoint.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/trigger/BitbucketWebhookTriggerImpl.java
- src/test/java/com/atlassian/bitbucket/jenkins/internal/trigger/BitbucketWebhookConsumerTest.java
- src/test/java/it/com/atlassian/bitbucket/jenkins/internal/trigger/BitbucketWebhookTriggerImplTest.java
* Made project key and repository slug matching case-insensitive.
* Changed usages of `sl4j` to `java.util.logging`
> Made project key and repository slug matching case-insensitive and sl4j improvements

- pom.xml
- src/main/java/com/atlassian/bitbucket/jenkins/internal/trigger/BitbucketTriggerWorker.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/trigger/BitbucketWebhookTriggerCause.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/trigger/BitbucketWebhookTriggerImpl.java
- src/test/java/com/atlassian/bitbucket/jenkins/internal/trigger/BitbucketTriggerWorkerTest.java
- src/test/java/com/atlassian/bitbucket/jenkins/internal/trigger/BitbucketWebhookTriggerCauseTest.java
- src/test/java/com/atlassian/bitbucket/jenkins/internal/trigger/BitbucketWebhookTriggerImplTest.java
Moved the Runner out to its own class and updated tests to not need sleeps etc to test the functionality.
> Move Runner to its own class to ease testing

- pom.xml
Enables clover reporting (in profile so we don't run it all the time)
> Enable clover

- pom.xml
This allows the versions plugin to update the versions with ease.
> Add profile with direct dependencies on Jenkins and Bitbucket.

- src/main/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketRequestExecutor.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/http/HttpRequestExecutorImpl.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/model/BitbucketRepository.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCM.java
If there is a configuration error we should not throw an exception because this will mean that everything else is not persisted. We should continue as much as possible to reduce the amount of work the user has to do to fix the error.
> Dont fail to save on error

- src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCM.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMStep.java
* Show BitbucketSCM when editing a pipeline
* Add missing `@QueryParameter` annotations for `doFillMirrorNameItems`
> Misc fixes

- readme.md
Hi. Please review my update to the readme. Thanks.
> update readme for beta 1

- src/main/java/com/atlassian/bitbucket/jenkins/internal/config/BitbucketServerConfiguration.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketScmFormValidationDelegate.java
- src/main/resources/com/atlassian/bitbucket/jenkins/internal/config/BitbucketPluginConfiguration/config.properties
- src/main/resources/com/atlassian/bitbucket/jenkins/internal/config/BitbucketServerConfiguration/config.groovy
- src/main/resources/com/atlassian/bitbucket/jenkins/internal/config/BitbucketServerConfiguration/config.properties
- src/main/resources/com/atlassian/bitbucket/jenkins/internal/config/BitbucketServerConfiguration/help-adminCredentialsId.html
- src/main/resources/com/atlassian/bitbucket/jenkins/internal/config/BitbucketServerConfiguration/help-baseUrl.html
- src/main/resources/com/atlassian/bitbucket/jenkins/internal/config/BitbucketServerConfiguration/help-credentialsId.html
- src/main/resources/com/atlassian/bitbucket/jenkins/internal/config/BitbucketServerConfiguration/help-serverName.html
- src/main/resources/com/atlassian/bitbucket/jenkins/internal/config/BitbucketTokenCredentialsImpl/config.groovy
- src/main/resources/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCM/config.groovy
- src/main/resources/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCM/config.properties
- src/main/resources/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCM/help-branchName.html
- src/main/resources/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCM/help-credentialsId.html
- src/main/resources/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCM/help-projectName.html
- src/main/resources/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCM/help-repositoryName.html
- src/main/resources/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCM/help-serverId.html
- src/main/resources/com/atlassian/bitbucket/jenkins/internal/trigger/BitbucketWebhookTriggerImpl/help.properties
This is based on the latest mural.
> Updated form copy to latest revision

- src/main/java/com/atlassian/bitbucket/jenkins/internal/status/BuildStatusPoster.java
- src/test/java/com/atlassian/bitbucket/jenkins/internal/status/BuildStatusPosterTest.java
since the non-admin credentials are optional and may not be present
> Update build status to use server admin credentials

- src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCM.java
- src/test/java/it/com/atlassian/bitbucket/jenkins/internal/fixture/TestSCM.java
To incorporate - https://github.com/jenkinsci/atlassian-bitbucket-server-integration-plugin/pull/81#discussion_r331793499
> Remove Guava annotation

- src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCM.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMStep.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketScmFormValidation.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketScmFormValidationDelegate.java
- src/main/resources/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCM/config.groovy
- src/main/resources/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCM/config.properties
- src/test/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketScmFormValidationDelegateTest.java
- src/test/java/it/com/atlassian/bitbucket/jenkins/internal/config/BitbucketProjectConfigurationIT.java
> Add test connection button to repo config

- pom.xml
> Add URL to pom.xml

- src/main/java/com/atlassian/bitbucket/jenkins/internal/http/HttpRequestExecutorImpl.java
Update plugin artifactId in HttpRequestExecutorImpl that was using the old artifactId. Also remove spaces from the UserAgent string
> JENKINS-60128 and JENKINS-60127

- src/test/java/it/com/atlassian/bitbucket/jenkins/internal/config/BitbucketPluginConfigurationIT.java
it now provides slightly more logging to help track down the flake. It also uses our existing waitfor rather than a custom one. It seems to have improved the situation, but given it is a flake it is hard to say for certain. I've ran it about 300 times locally (all pass) and multiple times in CI.
> Improving the flakey

- src/main/java/com/atlassian/bitbucket/jenkins/internal/status/BitbucketBuildStatusFactory.java
- src/test/java/com/atlassian/bitbucket/jenkins/internal/status/BitbucketBuildStatusFactoryTest.java
- src/test/java/com/atlassian/bitbucket/jenkins/internal/status/BuildStatusPosterTest.java
- src/test/java/it/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMIT.java
* Updated the integration test to verify the build posted had the projects name as key
> JENKINS-60956: Fix integration tests to verify build status posted to Bitbucket

- pom.xml
> Bump major version in POM

- src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCM.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMRepository.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketScmHelper.java
- src/test/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMTest.java
Addressing https://issues.jenkins-ci.org/browse/JENKINS-60274
> Display and use project key instead of name for private repos

- acceptance-tests/pom.xml
- acceptance-tests/readme.md
- acceptance-tests/src/main/java/it/com/atlassian/bitbucket/jenkins/internal/test/acceptance/ProjectBasedMatrixSecurityHelper.java
- acceptance-tests/src/test/java/it/com/atlassian/bitbucket/jenkins/internal/applink/oauth/ThreeLeggedOAuthAcceptanceTest.java
Adds a helper class for setting up (project-level matrix-based) security for tests with built-in auto-wired cleanup + some additional readme.
> test matrix-based security helper class with automated clean-up

- checkstyle-suppressions.xml
- checkstyle.xml
- src/main/java/com/atlassian/bitbucket/jenkins/internal/applink/oauth/OAuthConverter.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/applink/oauth/serviceprovider/auth/OAuth1aRequestFilter.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/applink/oauth/serviceprovider/auth/package-info.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/applink/oauth/serviceprovider/consumer/Consumer.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/applink/oauth/serviceprovider/consumer/package-info.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/applink/oauth/serviceprovider/package-info.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/jenkins/oauth/consumer/OAuthConsumerEntry.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/jenkins/oauth/consumer/OAuthConsumerUpdateAction.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/jenkins/oauth/consumer/package-info.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/jenkins/oauth/servlet/AuthorizeConfirmationConfig.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/jenkins/oauth/servlet/package-info.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/jenkins/oauth/token/package-info.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/provider/JenkinsProvider.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/provider/package-info.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMSource.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMStep.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/trigger/BitbucketWebhookTriggerImpl.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/util/package-info.java
- src/test/java/com/atlassian/bitbucket/jenkins/internal/applink/oauth/serviceprovider/consumer/PersistentServiceProviderConsumerStoreTest.java
- src/test/java/it/com/atlassian/bitbucket/jenkins/internal/applink/oauth/serviceprovider/consumer/PersistentServiceProviderConsumerStoreTest.java
- Added missing package-info.java files
- checkstyle for checking package-info.java in each package
- suppressed the check for src/test/*
- removed the unnecessary individual `@Nonnull` annotations
> Added missing package-info.java

- src/main/java/com/atlassian/bitbucket/jenkins/internal/applink/oauth/serviceprovider/consumer/PersistentServiceProviderConsumerStore.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/client/supply/package-info.java
Added missing package-info.java to pass checkstyle on commit.
> fixing the PersistentServiceProviderConsumerStoreTest

- readme.md
Addressing https://issues.jenkins-ci.org/browse/JENKINS-62057
> Added a warning about not using Jenkinsfiles

- src/test/java/it/com/atlassian/bitbucket/jenkins/internal/status/BuildStatusPosterIT.java
My slightly blasé merges on Wednesday broke our integration tests. This should green them.
> updated it build status shape

- pom.xml
Features going out in 2.0.0:
- Rich build statuses
- Fix for JENKINS-61915
- Fix for JENKINS-61411
> Updated pom to 2.0.0

- acceptance-tests/src/test/java/it/com/atlassian/bitbucket/jenkins/internal/SmokeTest.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMSource.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/trigger/BitbucketWebhookMultibranchTrigger.java
- src/test/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMSourceTest.java
- src/test/java/com/atlassian/bitbucket/jenkins/internal/trigger/BitbucketWebhookMultibranchTriggerTest.java
- src/test/java/it/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMSourceIT.java
- fixing the bug where creating a multi-branch job with Bitbucket SCM trigger doesn't create a webhook
- un-ignored the relevant smoke test
> JENKINS-63121: fixing the bug where creating a multi-branch job with Bitbucket SCM trigger doesn't create a webhook

- readme.md
- src/main/resources/com/atlassian/bitbucket/jenkins/internal/jenkins/oauth/consumer/OAuthConsumerEntry/config.jelly
- src/main/resources/com/atlassian/bitbucket/jenkins/internal/jenkins/oauth/consumer/OAuthConsumerEntry/help-callbackUrl.html
- src/main/resources/com/atlassian/bitbucket/jenkins/internal/jenkins/oauth/consumer/OAuthConsumerEntry/help-consumerKey.html
- src/main/resources/com/atlassian/bitbucket/jenkins/internal/jenkins/oauth/consumer/OAuthConsumerEntry/help-consumerName.html
- src/main/resources/com/atlassian/bitbucket/jenkins/internal/jenkins/oauth/consumer/OAuthConsumerEntry/help-consumerSecret.html
Hi @mhenschke-atl
As suggested by Kristy, I added in more detail to help customers when creating a new consumer. 
It's all based on the question mark help text you wrote, but I've tried to simplify a few things. 
Let me know what you think and we can potentially update the help text in Jenkins too. 
Cameron
> Update readme to clarify create new consumer steps

- src/main/java/com/atlassian/bitbucket/jenkins/internal/applink/oauth/serviceprovider/OAuthRequestUtils.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/applink/oauth/serviceprovider/rest/OauthCrumbExclusion.java
as they should be unprotected and have proper handling for these things already
> Add crumb exception for Oauth (applink) requests

- src/main/java/com/atlassian/bitbucket/jenkins/internal/config/BitbucketPluginConfiguration.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/config/BitbucketServerConfiguration.java
Compatibility with https://github.com/jenkinsci/jenkins/pull/4944.
> Avoid com.thoughtworks.xstream.annotations

- src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCM.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMRepository.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMSource.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMStep.java
This applies the same fix used here to MBP and Pipelines. Tested locally, but happy to make some func tests if they are warranted.
> JENKINS-60274 add personal repo support for mbp and pipeline

- src/main/java/com/atlassian/bitbucket/jenkins/internal/jenkins/oauth/consumer/OAuthGlobalConfiguration.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/jenkins/oauth/token/OAuthTokenConfiguration.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/jenkins/oauth/token/UserOAuthTokenTransientActionFactory.java
- src/main/resources/com/atlassian/bitbucket/jenkins/internal/jenkins/oauth/consumer/OAuthGlobalConfiguration/index.jelly
- src/main/resources/com/atlassian/bitbucket/jenkins/internal/jenkins/oauth/consumer/OAuthGlobalConfiguration/sidepanel.jelly
- src/main/resources/com/atlassian/bitbucket/jenkins/internal/jenkins/oauth/consumer/OAuthGlobalConfiguration/sidepanel.properties
- src/main/resources/com/atlassian/bitbucket/jenkins/internal/jenkins/oauth/token/Messages.properties
- src/main/resources/com/atlassian/bitbucket/jenkins/internal/jenkins/oauth/token/OAuthTokenConfiguration/sidepanel.properties
- src/test/java/com/atlassian/bitbucket/jenkins/internal/jenkins/oauth/token/OAuthTokenConfigurationTest.java
- src/test/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketJobLinkActionFactoryTest.java
> Added oauth action to user config sidepanel, updated messages to match

- src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMSource.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/trigger/register/PullRequestStoreImpl.java
- src/test/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMSourceTest.java
- src/test/java/com/atlassian/bitbucket/jenkins/internal/trigger/register/BitbucketWebhookHandlerTest.java
Features: 
- unit test for manual scan and refreshing pr store 
- improving implementation/code design of removing pull request from pr store, and pull request store test
> added unit tests and code improvements for closed events

- src/main/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketRepositoryClient.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketRepositoryClientImpl.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/model/BitbucketPullRequestRef.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMSource.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/SelectBranchTrait.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/trigger/BitbucketWebhookMultibranchTrigger.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/trigger/register/MinimalPullRequest.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/trigger/register/PullRequestStore.java
- src/test/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketRepositoryClientImplTest.java
A small one this time, only fixing some javadoc, and also a small refactor of the client snuck in for good measure
> Fix javadoc a bit

- src/main/java/com/atlassian/bitbucket/jenkins/internal/trigger/BitbucketWebhookConsumer.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/trigger/BitbucketWebhookEndpoint.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/trigger/BitbucketWebhookMultibranchTrigger.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/trigger/BitbucketWebhookTriggerImpl.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/trigger/events/BitbucketWebhookEvent.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/trigger/events/PullRequestFromRefUpdatedWebhookEvent.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/trigger/register/BitbucketWebhookHandler.java
- src/test/java/com/atlassian/bitbucket/jenkins/internal/trigger/BitbucketWebhookConsumerTest.java
- src/test/java/com/atlassian/bitbucket/jenkins/internal/trigger/BitbucketWebhookEndpointTest.java
- src/test/java/com/atlassian/bitbucket/jenkins/internal/trigger/register/BitbucketWebhookHandlerTest.java
Add support for the "Source branch updated" webhook. 
More comprehensive automated testing is coming as part of the last stage of this feature
> Add support for Source Branch updated event

- src/main/java/com/atlassian/bitbucket/jenkins/internal/trigger/register/BitbucketWebhookHandler.java
- src/test/java/com/atlassian/bitbucket/jenkins/internal/trigger/register/BitbucketWebhookHandlerTest.java
@KalleOlaviNiemitalo found  bug in how we updated webhooks. The test we had was a bit too simple. I've fixed this now and updated the test.
> Fix bug in webhook handling found by KalleOlaviNiemitalo

- src/main/resources/com/atlassian/bitbucket/jenkins/internal/trigger/BitbucketWebhookTriggerImpl/help-pullRequestTrigger.html
Remove the extra after after after
> Remove the extra after in the help text

- src/main/resources/com/atlassian/bitbucket/jenkins/internal/deployments/DeploymentNotifier/help-environmentUrl.html
- src/main/resources/com/atlassian/bitbucket/jenkins/internal/deployments/DeploymentStepImpl/help-environmentUrl.html
Removing these files as they are no longer used (see https://github.com/jenkinsci/atlassian-bitbucket-server-integration-plugin/pull/300).
> Remove unused inline help html

- src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMSource.java
Hopefully the first in a bunch of refactors of the SCM and SCMSource that are long overdue!
> Simplify retrieve in BitbucketSCMSource

- src/main/java/com/atlassian/bitbucket/jenkins/internal/link/BitbucketJobLinkActionFactory.java
- src/test/java/com/atlassian/bitbucket/jenkins/internal/link/BitbucketJobLinkActionFactoryTest.java
Non-multibranch pipeline jobs with SCM steps no longer link to a broken branch URL. Instead they will link to the repository directly
> JENKINS-67199 Non-multibranch pipeline job repository links

- src/test/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketCapabilitiesClientImplTest.java
Tiny mistake in my unit tests I caught after I merged...
> Small fix to unit tests'

- readme.md
- src/main/java/com/atlassian/bitbucket/jenkins/internal/config/BitbucketServerConfiguration.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/jenkins/oauth/consumer/OAuthConsumerCreateAction.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/jenkins/oauth/consumer/OAuthConsumerEntry.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/jenkins/oauth/consumer/OAuthConsumerUpdateAction.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/jenkins/oauth/consumer/OAuthGlobalConfiguration.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/util/FormValidationUtils.java
- src/main/resources/com/atlassian/bitbucket/jenkins/internal/jenkins/oauth/consumer/Messages.properties
- src/test/java/com/atlassian/bitbucket/jenkins/internal/jenkins/oauth/consumer/OAuthConsumerEntryTest.java
- src/test/java/com/atlassian/bitbucket/jenkins/internal/util/FormValidationUtilsTest.java
> Missing files from PR #335

- src/main/java/com/atlassian/bitbucket/jenkins/internal/jenkins/oauth/consumer/OAuthConsumerCreateAction.java
> Fixed failing upgrade tests

- src/main/java/com/atlassian/bitbucket/jenkins/internal/jenkins/oauth/consumer/OAuthConsumerCreateAction.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMStep.java
- src/test/resources/safeRemovedFields.txt
These are all now stale, just cleaning them up after the release
> Remove some upgrade annotations and removed fields that are no longer relevant

- src/main/java/com/atlassian/bitbucket/jenkins/internal/model/BitbucketMirroredRepository.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/model/BitbucketRepository.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCM.java
- src/test/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMTest.java
> Bugfix: JENKINS-68634 Clone from mirror clone URL when configured to clone from a mirror

- pom.xml
- src/test/java/it/com/atlassian/bitbucket/jenkins/internal/config/BitbucketProjectConfigurationIT.java
Add dependency on Jenkins test harness so that we're using an up-to-date version
> Fix bitbucket project configuration it

- acceptance-tests/src/main/java/it/com/atlassian/bitbucket/jenkins/internal/util/BitbucketUtils.java
* OpenSSH has deprecated RSA keypair authentication. We are manually
creating the keypair because currently jenkins-ci acceptance test
library can only create RSA keys.
> Switch to using ed25519 instead of rsa keypair

- src/main/java/com/atlassian/bitbucket/jenkins/internal/jenkins/oauth/consumer/OAuthConsumerEntry.java
- src/test/java/com/atlassian/bitbucket/jenkins/internal/jenkins/oauth/consumer/OAuthConsumerEntryTest.java
> JENKINS-69288 updated consumer key validation message when using non-alpha characters

- readme.md
- src/main/java/com/atlassian/bitbucket/jenkins/internal/jenkins/oauth/consumer/OAuthConsumerEntry.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/trigger/BitbucketWebhookConsumer.java
- src/test/java/com/atlassian/bitbucket/jenkins/internal/jenkins/oauth/consumer/OAuthConsumerEntryTest.java
- src/test/java/com/atlassian/bitbucket/jenkins/internal/trigger/BitbucketWebhookConsumerTest.java
This reverts commit 2f9d907cf019c6b6e8e2328eca3db8f725e60904.
> Revert "Mh/revert/3.3.0 (#360)"

- pom.xml
> Upgrade Jackson to latest version

- src/main/java/com/atlassian/bitbucket/jenkins/internal/status/BuildStatusPoster.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/status/LocalSCMListener.java
- src/test/java/com/atlassian/bitbucket/jenkins/internal/status/LocalSCMListenerTest.java
- src/test/resources/mockito-extensions/org.mockito.plugins.MockMaker
Removes inline mocking in `LocalSCMListenerTest` for 4 tests. Formatting to comply with our checkstyle
> Remove inline mocking

- readme.md
Updating release notes to include fix for https://issues.jenkins.io/browse/JENKINS-69268 and to remove references to release 3.3.4.
> NONE-update readme for release 3.3.3

- src/main/webapp/js/searchableField.js
Remove Prototype Ajax.Request from searchableField.js in favor of the JavaScript fetch API.
> JENKINS-71300 Remove Prototype Ajax.Request from searchableField.js

- acceptance-tests/pom.xml
- pom.xml
Update pom.xml & Acceptance-tests/pom.xml to use the new 4.0.0-SNAPSHOT
> Update VERSION to 4.0.0-SNAPSHOT

- src/main/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketFilePathClient.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketFilePathClientImpl.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketPullRequestSCMHead.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMHead.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMProbe.java
- src/test/java/com/atlassian/bitbucket/jenkins/internal/client/BitbucketFilePathClientImplTest.java
Add initial SCMProbe implementation which uses Bitbucket's REST API to check if a file exists.
> Add initial SCMProbe implementation

- acceptance-tests/src/main/java/it/com/atlassian/bitbucket/jenkins/internal/pageobjects/BitbucketScmConfig.java
- acceptance-tests/src/main/java/it/com/atlassian/bitbucket/jenkins/internal/pageobjects/BitbucketScmWorkflowJob.java
- acceptance-tests/src/main/java/it/com/atlassian/bitbucket/jenkins/internal/util/BrowserUtils.java
This attempts to fix the smoke tests which have been flaky recently.
> Fix flaky smoke tests

- src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMSource.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/CustomGitSCMSource.java
Implement retrieve that gets the revision of the specified head.
> Implement retrieve that gets the revision of the specified head

- pom.xml
- src/main/java/com/atlassian/bitbucket/jenkins/internal/model/BitbucketPullRequest.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMSource.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/MinimalPullRequest.java
- src/test/java/com/atlassian/bitbucket/jenkins/internal/link/BitbucketJobLinkActionFactoryTest.java
- src/test/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketPullRequestDiscoveryTraitTest.java
- src/test/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMSourceTest.java
Adds an `ObjectMetadataAction` with the PR title and description for heads of`BitbucketPullRequestSCMHead` type.
> Add ObjectMetadataAction with PR title and description

- pom.xml
- readme.md
Prep pom.xml and changelog for alpha release.
> Prep for alpha release

- src/main/webapp/js/searchableField.js
See https://github.com/jenkinsci/jenkins/pull/8279. There is no user-visible bug here, nor is there any security problem. But the code did not conform to best practices. This PR is a code cleanup PR to make the code conform to best practices. There is no urgent need to merge and release it.
> Pass POST parameters in body rather than query string

- acceptance-tests/pom.xml
- pom.xml
- readme.md
Fixes https://github.com/jenkinsci/atlassian-bitbucket-server-integration-plugin/security/dependabot/38
> Update minimum Jenkins version to 2.401.3

- src/test/java/it/com/atlassian/bitbucket/jenkins/internal/config/BitbucketPluginConfigurationIT.java
- src/test/java/it/com/atlassian/bitbucket/jenkins/internal/util/HtmlUnitUtils.java
Fixes our test for latest Jenkins. Not super happy with it, but it does make all the tests go green
> Tweak tests to work with new Jenkins html structure

- src/test/java/com/atlassian/bitbucket/jenkins/internal/client/ModernBitbucketBuildStatusClientImplTest.java
adapt to [removal of JCIFS](https://github.com/jenkinsci/jenkins/pull/8523) from Jenkins core by changing implementation in test.
```[tasklist]
```
> switch to Base64 to stock java implementation

- src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketScmFormFillDelegate.java
- src/test/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketScmFormFillDelegateTest.java
- src/test/java/it/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMDescriptorIT.java
In Bitbucket 9.0+, repository/project search requests (made without providing credentials) are considered unauthorised (and [HttpRequestExecutorImpl throws an AuthorizationException](https://github.com/jenkinsci/atlassian-bitbucket-server-integration-plugin/blob/atlassian-bitbucket-server-integration-4.0.0/src/main/java/com/atlassian/bitbucket/jenkins/internal/http/HttpRequestExecutorImpl.java#L134-L137) when that happens), unless the Bitbucket instance has a public repository/project. Pre 9.0, they'd be allowed. 
This PR changes Jenkins' FormFillDelegate to respond with 401s (instead of 500) when no credentials are supplied and Bitbucket doesn't have public access, when searching for project/repo names whilst filling out the configuration form.
The existing behavior already provides a …
> Update repository/project name form fillers to handle requests being considered unauthorised by Bitbucket 9.0+

- src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMSource.java
- src/test/java/it/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMSourceIT.java
This PR fixes https://issues.jenkins.io/browse/JENKINS-72765 which appears to be caused when Jenkins restarts while Bitbucket is down.
* Integration test added
* Tested on our internal Jenkins/Bitbucket dev server by stopping Bitbucket, restarting jenkins, and starting Bitbucket
- [X ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ X] Ensure that the pull request title represents the desired changelog entry
- [ X] Please describe what you did
- [ X] Link to relevant issues in GitHub or Jira
- [ X] Link to relevant pull requests, esp. upstream and downstream changes
- [ X] Ensure you have provided tests - that demonstrates feature works or fixes the issue
> Fix the unstable config in JENKINS-72765

- src/main/java/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMSource.java
- src/test/java/it/com/atlassian/bitbucket/jenkins/internal/scm/BitbucketSCMSourceIT.java
Fix style violations and minor whitespace fix
> Fix checkstyle issues

- readme.md
Adds the changelog entry for the recently released `4.1.2`
Includes fixes for: 
* https://issues.jenkins.io/browse/JENKINS-73871
* https://issues.jenkins.io/browse/JENKINS-74782
> NONE - Update Changelog for 4.1.2

- pom.xml
Automatic release failed. Reverting prepare and will release manually.
> Revert 4.1.3

- readme.md
Updating the readme to reflect the Jenkins version in the pom.xml
> Update readme to reflect actual minimum Jenkins version

- pom.xml
- readme.md
PR with the changes for the local release of the plugin.
> Local release & bump plugin to 4.1.3

- readme.md
Small PR updating the changelog advising of the security fix.
> Update changelog with 4.1.4 changes

- src/main/java/com/atlassian/bitbucket/jenkins/internal/applink/oauth/serviceprovider/OAuthRequestUtils.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/applink/oauth/serviceprovider/auth/OAuth1Authenticator.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/applink/oauth/serviceprovider/auth/OAuth1aRequestFilter.java
- src/main/java/com/atlassian/bitbucket/jenkins/internal/applink/oauth/serviceprovider/rest/OauthCrumbExclusion.java
- src/test/java/com/atlassian/bitbucket/jenkins/internal/applink/oauth/serviceprovider/rest/OauthCrumbExclusionTest.java
Whitespace fixes plus a scattering of moving some code around in the same file. All up this makes the code comply with the code style for the repository.
> Fix code style

- src/main/java/com/atlassian/bitbucket/jenkins/internal/applink/oauth/serviceprovider/rest/OauthCrumbExclusion.java
This pull request aims to close [https://issues.jenkins.io/browse/JENKINS-75365](url).<br>
Previously, the `getBuilds` method only generated URL's for freestyle projects because `Project.class` was being used. This meant that you could not manually build a multibranch pipeline job from Bitbucket as this URL was not generated by `getBuilds` and therefore meant the build request was not excluded from CSRF protection as expected.<br>
`Job.class` however includes all types of jobs which means all expected build URL's are included in this list and excluded from CSRF protection.
The proposed changes were made locally, built and installed on a Jenkins system. I confirmed that I was now able to manually build freestyle, pipeline, and multibranch pipeline projects from Bitbucket.
> JENKINS-75365: Fixes manually building all types of projects from Bitbucket

- acceptance-tests/pom.xml
- pom.xml
- readme.md
Update the changelog and pom version for the next release.
> Prepare for next release

- src/test/java/upgrade/com/atlassian/bitbucket/jenkins/internal/UpgradeTest.java
https://server-syd-bamboo.internal.atlassian.com/browse/BSERVTOOLS-BBSJEN-1099
> BBSDEV-34436 - Fix checkstyle error
